"""empty message

Revision ID: 312b8485ce15
Revises: 1ade9d8fae7e
Create Date: 2021-09-06 17:04:23.198702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312b8485ce15'
down_revision = '1ade9d8fae7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'value')
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('tags', sa.Column('value', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
