"""empty message

Revision ID: 3c18beeaea47
Revises: 5cb61ee0b514
Create Date: 2021-08-30 15:14:51.218384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c18beeaea47'
down_revision = '5cb61ee0b514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    op.drop_table('follows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['terms.id'], name='follows_followed_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['terms.id'], name='follows_follower_id_fkey'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id', name='follows_pkey')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
