"""empty message

Revision ID: 3d3ed0485335
Revises: e82aaf1493ec
Create Date: 2021-08-31 16:58:27.010794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3ed0485335'
down_revision = 'e82aaf1493ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('value', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'value')
    # ### end Alembic commands ###
