"""empty message

Revision ID: 46ed1a111fd1
Revises: 5580c16f3ecf
Create Date: 2021-08-23 21:56:16.485933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ed1a111fd1'
down_revision = '5580c16f3ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terms', 'examples')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms', sa.Column('examples', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
