"""empty message

Revision ID: 51c5197954a6
Revises: defa9fb015c0
Create Date: 2021-09-10 18:04:10.863924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c5197954a6'
down_revision = 'defa9fb015c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('tags', sa.Column('value', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'value')
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###
