"""empty message

Revision ID: 5580c16f3ecf
Revises: d7c3174479f8
Create Date: 2021-08-23 19:51:59.149651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5580c16f3ecf'
down_revision = 'd7c3174479f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('tracker_id', sa.Integer(), nullable=False))
    op.add_column('tracks', sa.Column('tracked_id', sa.Integer(), nullable=False))
    op.drop_constraint('tracks_tracking_fkey', 'tracks', type_='foreignkey')
    op.drop_constraint('tracks_tracker_fkey', 'tracks', type_='foreignkey')
    op.create_foreign_key(None, 'tracks', 'terms', ['tracked_id'], ['id'])
    op.create_foreign_key(None, 'tracks', 'users', ['tracker_id'], ['id'])
    op.drop_column('tracks', 'tracking')
    op.drop_column('tracks', 'tracker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('tracker', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tracks', sa.Column('tracking', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.create_foreign_key('tracks_tracker_fkey', 'tracks', 'users', ['tracker'], ['id'])
    op.create_foreign_key('tracks_tracking_fkey', 'tracks', 'terms', ['tracking'], ['id'])
    op.drop_column('tracks', 'tracked_id')
    op.drop_column('tracks', 'tracker_id')
    # ### end Alembic commands ###
