"""empty message

Revision ID: 567326bff1ae
Revises: c04c4281d533
Create Date: 2021-09-01 08:35:41.506551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567326bff1ae'
down_revision = 'c04c4281d533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'timestamp')
    # ### end Alembic commands ###
