"""empty message

Revision ID: 5c157ad180f1
Revises: f8ad328b4eeb
Create Date: 2021-09-02 10:16:08.106148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c157ad180f1'
down_revision = 'f8ad328b4eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_message_read_time')
    # ### end Alembic commands ###
