"""empty message

Revision ID: 5e660920a238
Revises: 3c18beeaea47
Create Date: 2021-08-31 15:53:19.129347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e660920a238'
down_revision = '3c18beeaea47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('terms_term_key', 'terms', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('terms_term_key', 'terms', ['term'])
    # ### end Alembic commands ###
