"""empty message

Revision ID: 64a043085b1c
Revises: be4c85b26628
Create Date: 2021-08-25 19:36:40.352547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a043085b1c'
down_revision = 'be4c85b26628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('parent_id', sa.Integer(), nullable=False))
    op.add_column('relationships', sa.Column('child_id', sa.Integer(), nullable=False))
    op.drop_constraint('relationships_subject_id_fkey', 'relationships', type_='foreignkey')
    op.drop_constraint('relationships_object_id_fkey', 'relationships', type_='foreignkey')
    op.create_foreign_key(None, 'relationships', 'terms', ['child_id'], ['id'])
    op.create_foreign_key(None, 'relationships', 'terms', ['parent_id'], ['id'])
    op.drop_column('relationships', 'object_id')
    op.drop_column('relationships', 'subject_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('relationships', sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.create_foreign_key('relationships_object_id_fkey', 'relationships', 'terms', ['object_id'], ['id'])
    op.create_foreign_key('relationships_subject_id_fkey', 'relationships', 'terms', ['subject_id'], ['id'])
    op.drop_column('relationships', 'child_id')
    op.drop_column('relationships', 'parent_id')
    # ### end Alembic commands ###
