"""empty message

Revision ID: ad5d98088ec8
Revises: 103836877cea
Create Date: 2021-08-31 16:05:23.933021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5d98088ec8'
down_revision = '103836877cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term_tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], )
    )
    op.add_column('tags', sa.Column('slug', sa.String(length=64), nullable=True))
    op.drop_constraint('tags_name_key', 'tags', type_='unique')
    op.create_unique_constraint(None, 'tags', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.create_unique_constraint('tags_name_key', 'tags', ['name'])
    op.drop_column('tags', 'slug')
    op.drop_table('term_tags')
    # ### end Alembic commands ###
