"""empty message

Revision ID: b42062867f90
Revises: 197f6f32d02e
Create Date: 2021-08-23 15:34:29.418454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42062867f90'
down_revision = '197f6f32d02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms', sa.Column('source', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terms', 'source')
    # ### end Alembic commands ###
