"""empty message

Revision ID: be4c85b26628
Revises: 5eecdbeeb08f
Create Date: 2021-08-25 19:15:10.913315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4c85b26628'
down_revision = '5eecdbeeb08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('predicate', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['terms.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('object_id', 'subject_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    # ### end Alembic commands ###
