"""empty message

Revision ID: c04c4281d533
Revises: d370b9c07324
Create Date: 2021-09-01 02:56:08.262699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04c4281d533'
down_revision = 'd370b9c07324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_tags')
    op.add_column('tags', sa.Column('term_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'terms', ['term_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'term_id')
    op.create_table('t_tags',
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('term_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='t_tags_tag_id_fkey'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name='t_tags_term_id_fkey')
    )
    # ### end Alembic commands ###
