"""empty message

Revision ID: d370b9c07324
Revises: 3d3ed0485335
Create Date: 2021-09-01 02:45:18.703703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd370b9c07324'
down_revision = '3d3ed0485335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], )
    )
    op.drop_table('term_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term_tags',
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('term_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='term_tags_tag_id_fkey'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name='term_tags_term_id_fkey')
    )
    op.drop_table('t_tags')
    # ### end Alembic commands ###
