"""empty message

Revision ID: d77f88e3119b
Revises: 312b8485ce15
Create Date: 2021-09-06 17:04:33.928463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77f88e3119b'
down_revision = '312b8485ce15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('tags', sa.Column('value', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'value')
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###
