"""empty message

Revision ID: d7c3174479f8
Revises: b42062867f90
Create Date: 2021-08-23 18:24:04.438852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c3174479f8'
down_revision = 'b42062867f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('tracker', sa.Integer(), nullable=False),
    sa.Column('tracking', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tracker'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tracking'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('tracker', 'tracking')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    # ### end Alembic commands ###
