"""empty message

Revision ID: defa9fb015c0
Revises: 
Create Date: 2021-09-10 18:03:53.680211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defa9fb015c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'name')
    op.drop_column('tags', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('value', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('tags', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
