"""empty message

Revision ID: e82aaf1493ec
Revises: ad5d98088ec8
Create Date: 2021-08-31 16:09:57.977634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82aaf1493ec'
down_revision = 'ad5d98088ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms', sa.Column('created_timestamp', sa.DateTime(), nullable=True))
    op.add_column('terms', sa.Column('modified_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terms', 'modified_timestamp')
    op.drop_column('terms', 'created_timestamp')
    # ### end Alembic commands ###
