"""empty message

Revision ID: f8ad328b4eeb
Revises: 567326bff1ae
Create Date: 2021-09-01 08:40:06.812852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ad328b4eeb'
down_revision = '567326bff1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_slug_key', 'tags', type_='unique')
    op.drop_column('tags', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('slug', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_unique_constraint('tags_slug_key', 'tags', ['slug'])
    # ### end Alembic commands ###
